### ISSUE TITLE
[Method obfuscation]

### ISSUE THREAD

**Issue by CakeProgress** [terminalsin/skidfuscator-java-obfuscator#13]
Please, add method obfuscations, thanks.

**Comment by terminalsin** [comment]
Hello CakeProgress,

![kek](https://ih1.redbubble.net/image.1379685105.1268/fpp,small,lustre,wall_texture,product,750x1000.jpg)

Regards,
The Skidfuscator Team

**Comment by xThorlak** [comment]
Hello terminalsin, 
![image](https://user-images.githubusercontent.com/62741667/145104266-9099ad3c-bfeb-4301-baa2-91e86bce1e0d.png)

**Comment by NikV2** [comment]
I like turtles.
