### ISSUE TITLE
Cannot use maple-ir dependency.

### ISSUE THREAD

**Issue by majigg** [terminalsin/skidfuscator-java-obfuscator#14]
I have tried using every version on Jitpack along with the forked version in the Discord. No matter what I use, some methods or classes are missing, such as `isNative()` and `isAbstract()` from `MethodNode`, along with many others. What version of maple-ir should I be using, and where do I get it?

**Comment by terminalsin** [comment]
You’re probably using the original one. Try using my fork available on my github profile using the git branch “memes/production-ready”

**Comment by majigg** [comment]
I was previously doing this, was this correct?
```mvn
<dependency>
            <groupId>com.github.terminalsin.maple-ir</groupId>
            <artifactId>app-services</artifactId>
            <version>1.0.9</version>
</dependency>
 ```

**Comment by terminalsin** [comment]
No. You’re looking to import the main module instead.

**Comment by majigg** [comment]
Thanks for your help :)

**Comment by terminalsin** [comment]
Glad to be of help!
