### ISSUE TITLE
Brute force interpolated obfuscation (Multithreaded)

### ISSUE THREAD

**Issue by NikV2** [terminalsin/skidfuscator-java-obfuscator#15]
**Is your feature request related to a problem? Please describe.**
It is related to many problems.

**Describe the solution you'd like**
Brute forcing the interpolation is the future.

**Describe alternatives you've considered**
ArtemisAC

**Additional context**
Please take this into consideration, Elon musk invented this and it is already being used
In plenty of public projects such as NASA or Tesla.

Thanks in advance, Yours sincirely Nik.

Here's the mathematical formula:
```java
600 * 14 / 73 + 41 - 512 + CACHED_RANDOM * 500 / 2 * 2
 / (Double.NEGATIVE_INFINITY * 1.00000D) * 9412 % 1 / (Double.MAX_EXPONENT * 1.00000D)
% 1 * 599D / 2 % 96 + 1D * 9521 / 2 * 200 % .7 / 2 * 2000
% 1 * 4.71D / 2 * CACHED_RANDOM * .001D % 61 / 5 * 421D
/ 600 * 14 / 73 + 41 - 512 + CACHED_RANDOM * 500 / 2 * 2
% 1 * 599D / 2 % 96 + 1D * 9521 / 2 * 200 % .7 / 2 * 2000
* 50 % 2 / 6113 * (Math.PI * 1.00000D) / (Math.E * 1.00000D) * 5000 % Math.random() * .2
/ (Double.NEGATIVE_INFINITY * 1.00000D) * 9412 % 1 / (Double.MAX_EXPONENT * 1.00000D)
 / 100 / (Double.NEGATIVE_INFINITY * 1.00000D) * 9412 % 1 / (Double.MAX_EXPONENT * 1.00000D)
/ 600 * 14 / 73 + 41 - 512 + CACHED_RANDOM * 500 / 2 * 2
/ (Double.NEGATIVE_INFINITY * 1.00000D) * 9412 % 1 / (Double.MAX_EXPONENT * 1.00000D)
% 1 * 4.71D / 2 * CACHED_RANDOM * .001D % 61 / 5 * 421D
/ (Double.NEGATIVE_INFINITY * 1.00000D) * 9412 % 1 / (Double.MAX_EXPONENT * 1.00000D)
% 1 * 599D / 2 % 96 + 1D * 9521 / 2 * 200 % .7 / 2 * 2000```

**Comment by NikV2** [comment]
**EDIT**

This issue is related to these two, Made by Generic and Electrum in the AliceAPI.

https://github.com/NikV2/AliceAPI/issues/29
https://github.com/NikV2/AliceAPI/issues/52

**Comment by NikV2** [comment]
![9](https://user-images.githubusercontent.com/61439310/146224109-85d45a9c-ae30-4569-8e10-e4b5b515dca1.png)

Almost forgot about this.

**Comment by terminalsin** [comment]
Added in f0c60ffb1d6bd1ee91c699d6dc326f962bec353e
