### ISSUE TITLE
error in opening zip file

### ISSUE THREAD

**Issue by KzSenR** [terminalsin/skidfuscator-java-obfuscator#28]
![}QPSTV}V}T4M}N14B7X(B09](https://user-images.githubusercontent.com/105924475/175818062-c068294b-7295-4f8b-96ff-1ab66ec76448.png)

**Comment by terminalsin** [comment]
You’re not obfuscating a jar file

**Comment by KzSenR** [comment]
![image](https://user-images.githubusercontent.com/105924475/175819727-c3c64c53-7593-45dc-ab76-d531861b4257.png)
![image](https://user-images.githubusercontent.com/105924475/175819740-4adbbce5-023c-42ee-b90e-9c87b7507200.png)
![image](https://user-images.githubusercontent.com/105924475/175819756-7b6dd423-02d5-4c3e-9527-f40e7253aa9e.png)
i dont know how to do

**Comment by KzSenR** [comment]
jar file is not null,and i dont know why obfuscator cant find it

**Comment by terminalsin** [comment]
We don’t have a config system yet. Point to your jar, not the config.

**Comment by terminalsin** [comment]
java -jar skidfuscator.jar awareline.jar

**Comment by KzSenR** [comment]
java -jar skidfuscator.jar awareline.jar was successful, but i dont know how to add my jar libraries?
![image](https://user-images.githubusercontent.com/105924475/175820521-e65e2f1e-a73d-4447-8072-2bfad9953557.png)

**Comment by KzSenR** [comment]
I solved the lib problem, thank you

**Comment by terminalsin** [comment]
np. Join the discord if you need any additional support 👍
