### ISSUE TITLE
compiled version

### ISSUE THREAD

**Issue by rambo1337977** [terminalsin/skidfuscator-java-obfuscator#3]
compiled version please.

**Comment by terminalsin** [comment]
Join the discord I’ll publish it soon with documentation

**Comment by rambo1337977** [comment]
can you send the discord? 
thanks.

**Comment by TypicalModMaker** [comment]
https://discord.gg/JEBD8afN

**Comment by modern158** [comment]
https://discord.gg/JEBD8afN
Discord here
